//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsNorway
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Airports = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Arrivals = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Departures = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_tab_airports = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_tab_arrivals = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_tab_departures = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int fra = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int gate = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int merknad = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int rute = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int text = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int tid = 2131034113;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int list_flight = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int list_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
